LoadModule _1cws_module /opt/1cv8/current/wsap24.so
AddHandler 1cws-process .1ccr

Alias /crs "/home/usr1cv8/.1cv8/crsweb"
<Directory "/home/usr1cv8/.1cv8/crsweb">
    AllowOverride All
    Require all granted
    Order allow,deny
    Allow from all
    SetHandler 1cws-process
</Directory>
